### ISSUE TITLE
Unexpected exception in show operation: 'module' object has no attribute 'sign'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/google-bigquery#156]
```
What steps will reproduce the problem?
1. gcloud auth activate-service-account ...@developer.gserviceaccount.com 
--key-file <path_to_key_file>.p12  --prompt-for-password
(Autorize the service account)

2. Execute any basic command like (bq show)

3. --> Unexpected exception in show operation: 'module' object has no attribute 
'sign'

What is the expected output? What do you see instead?

It should show the structure of the table. It is working fine when using my own 
account i.e. akansha.jawanpuria@intel.com

But, when I am using the service account - It is giving me an error: 
Unexpected exception in show operation: 'module' object has no attribute 'sign'


What version of the product are you using? On what operating system?

Product used : Google Cloud SDK 0.9.32 ; bq 2.0.18
Working on : CentOS release 6.4 with python 2.6.6 installed
             Also have pyOpenSSL installed and CLOUDSDK_PYTHON_SITEPACKAGES set to 1.


Please provide any additional information below.
Paste of output :

 bq show 87124197.ga_sessions_20140811
You have encountered a bug in the BigQuery CLI. Please file a bug report in our 
public issue tracker:
https://code.google.com/p/google-bigquery/issues/list
Please include a brief description of the steps that led to this issue, as well 
as the following information:

========================================
== Platform ==
  CPython:2.6.6:Linux-2.6.32-358.el6.x86_64-x86_64-with-centos-6.4-Final
== bq version ==
  2.0.22
== Command line ==
  ['/home/ajawanpu/google-cloud-sdk/platform/bq/bq.py', '--credential_file', '/home/ajawanpu/.config/gcloud/legacy_credentials/383444625864-6r8qmthfu0lejjesqhs4jrb4ep06l4pr@developer.gserviceaccount.com/singlestore.json', '--project', 'modern-impulse-666', 'show', '87124197.ga_sessions_20140811']
== UTC timestamp ==
  2014-09-29 10:02:56
== Error trace ==
  File "/home/ajawanpu/google-cloud-sdk/platform/bq/bq.py", line 711, in RunSafely
    return_value = self.RunWithArgs(*args, **kwds)
  File "/home/ajawanpu/google-cloud-sdk/platform/bq/bq.py", line 1657, in RunWithArgs
    object_info = client.GetObjectInfo(reference)
  File "/home/ajawanpu/google-cloud-sdk/platform/bq/bigquery_client.py", line 753, in GetObjectInfo
    return self.apiclient.tables().get(**dict(reference)).execute()
  File "/home/ajawanpu/google-cloud-sdk/platform/bq/bigquery_client.py", line 308, in execute
    return super(BigqueryHttp, self).execute(**kwds)
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ajawanpu/google-cloud-sdk/lib/apiclient/http.py", line 716, in execute
    body=self.body, headers=self.headers)
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/client.py", line 475, in new_request
    self._refresh(request_orig)
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/client.py", line 663, in _refresh
    self._do_refresh_request(http_request)
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/client.py", line 677, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/client.py", line 861, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/client.py", line 977, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/crypt.py", line 294, in make_signed_jwt
    signature = signer.sign(signing_input)
  File "/home/ajawanpu/google-cloud-sdk/lib/oauth2client/crypt.py", line 112, in sign
    return crypto.sign(self._key, message, 'sha256')
========================================

Unexpected exception in show operation: 'module' object has no attribute 'sign'


```

Original issue reported on code.google.com by `akansha....@intel.com` on 29 Sep 2014 at 10:07

Attachments:
- [bug.JPG](https://storage.googleapis.com/google-code-attachments/google-bigquery/issue-156/comment-0/bug.JPG)

**Comment by GoogleCodeExporter** [comment]
```
This is a very old version of the SDK; please reopen if this is still an issue. 
 Thanks!
```

Original comment by `thomasp...@google.com` on 25 Nov 2015 at 1:08
- Changed state: **Invalid**
